---
title: "NYC_energy_project"
runtime: shiny
output: html_document
---

```{r setup, include=FALSE}
require(rgdal)
require(leaflet)
require(leaflet.extras)
require(dplyr)
require(stringr)
```

```{r, polygon}
# Load csv data
eep_data <- read.csv("Energy_Efficiency_Projects.csv", stringsAsFactors = FALSE, colClasses = c("Postcode" = "character"))[,1:13]
eep_data <- na.omit(eep_data)
# Get all project types
type <- unique(eep_data$PrimaryProjectType)
# Calculte average emission in each area by zipcode
eep_co2 <- group_by(eep_data, Postcode)
summary <- summarise(eep_co2, mean=mean(CO2e..MT..Calculated))
# Load nyc map data
nyc.load <- readOGR("https://raw.githubusercontent.com/fedhere/PUI2015_EC/master/mam1612_EC/nyc-zip-code-tabulation-areas-polygons.geojson")
# Combine map with average emission by zipcode
nyc <- nyc.load[nyc.load$postalCode %in% summary$Postcode,]
nyc@data <- merge(nyc@data, summary, sort = FALSE, by.x = "postalCode", by.y = "Postcode")

# Map characters definition
bin_polygon <- c(0, 50, 100, 200, 500, Inf)
pal_polygon <- colorBin("PuRd", domain = nyc$mean, bins = bin_polygon)
pal_point <- colorFactor(c("Paired"), c(type))  

# Plot map
leaflet() %>%
  # Basemaps
  addTiles(group = "OSM (default)") %>%
  addProviderTiles("Esri.WorldStreetMap", group = "Esri World") %>%
  addProviderTiles("Stamen.TonerLite", group = "Toner Lite") %>%
  # Overlay groups: polygon
  addPolygons(  
    data = nyc,
    fillColor = ~pal_polygon(mean),
    popup = ~paste0("<b>", nyc$Postcode, ":</b> ", nyc$mean, "Metric Tons"),
    weight = 2,
    opacity = 1,
    color = "blue",
    dashArray = "3",
    fillOpacity = 0.8,
    highlight = highlightOptions(
      weight = 5,
      color = "#FFFFFF",
      dashArray = "",
      fillOpacity = 1,
      bringToFront = TRUE),
    group = "CO2 Emission") %>%
  addLegend(
    position = "bottomright",
    opacity = 0.8,
    pal = pal_polygon, 
    values = nyc$mean, 
    title = "Average GHG(CO2) Emissions (Unit: MT)",
    group = "CO2 Emission") %>%
  
  # Overlay groups: circle markers
  addCircleMarkers(
    data = eep_data,
    lng = ~Longitude, lat = ~Latitude, 
    radius = 3, 
    color = ~pal_point(PrimaryProjectType),
    fillOpacity = 1,
    clusterOptions = markerClusterOptions(removeOutsideVisibleBounds = FALSE),
    group = "Project Type"
    ) %>%
  addLegend(
    position = "topleft", 
    pal = pal_point, 
    values = eep_data$PrimaryProjectType, 
    title = "Project Type",
    group = "Project Type") %>%
  
  # Layers control
  addLayersControl(
    baseGroups = c("OSM (default)", "Esri World", "Toner Lite"),
    overlayGroups = c("CO2 Emission", "Project Type"),
    options = layersControlOptions(collapsed = FALSE)
  )


```


```{r, marker, lines}
eep_data <- read.csv("Energy_Efficiency_Projects.csv", stringsAsFactors = FALSE, colClasses = c("Postcode" = "character"))[,1:13]
eep_data <- na.omit(eep_data)

# Group data by borough
borough <- unique(eep_data$Borough)

pal_line <- colorFactor(c("Dark2"), c(borough))
m <- leaflet() %>% 
  addProviderTiles("Esri.WorldStreetMap") %>%
  addCircleMarkers(
    data = eep_data,
    lng = ~Longitude, lat = ~Latitude, 
    radius = 3, 
    color = ~pal_line(Borough),
    fillOpacity = 0.8
    ) %>%
  addLegend(
  position = "topleft", 
  pal = pal_line, 
  values = eep_data$Borough, 
  title = "Borough")

# Line all points in each borough
for(area in borough){
  borough_data <- eep_data[eep_data$Borough==area,]
  m = addPolylines(m,
                 data = borough_data,
                 lng= ~ Longitude,
                 lat= ~ Latitude,
                 color= ~pal_line(Borough),
                         weight = 1)
}
# Show map
m
```
